dist: xenial
language: python
cache: pip

python:
 - "3.7"

install:
 - pip install -U black flake8 flake8-assertive flake8-bugbear flake8-comprehensions

script:
 # Static analysis
 - flake8
 - black --check --diff .

matrix:
  fast_finish: true
